site_name: cdi
site_description: 'Beispiele zum Kurs: [DevOps Engineering Practices & Tools (CDI)]'
repo_url: https://github.com/mc-b/cdi
edit_uri: edit/main

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'README.md'  

docs_dir: cdi

nav:
  - Einleitung: cdi/README.md
  - Infrastruktur: cdi/02-Infrastruktur/README.md
  - Build: 03-Build/README.md
  - SCM: 04-SCM/README.md
  - CI: ../05-CI/README.md
  - Testen: ../06-Test/README.md
  - Deployment: ../07-CD/README.md
  
