pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd 06-Test/my-app; mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'cd 06-Test/my-app; mvn test'
            }
            post {
                always {
                  junit 'cd 06-Test/my-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Test Analyse') {
            steps {
                sh 'cd 06-Test/my-app; mvn cobertura:cobertura'
            }
            post {
                always {
                  cobertura coberturaReportFile: 'cd 06-Test/my-app/target/site/cobertura/coverage.xml'
                }
            }
        }
        stage('Code Analyse') {
            steps {
                sh 'cd 06-Test/my-app; mvn checkstyle:checkstyle'
            }
            post {
                always {
                  checkstyle pattern: 'cd 06-Test/my-app/target/checkstyle-result.xml'
                }
            }
        }
    }
}
