# CDI values for jenkins.

# For FQDN resolving of the controller service. Change this value to match your existing configuration.
# ref: https://github.com/kubernetes/dns/blob/master/docs/specification.md
clusterZone: "microk8s-cluster"

controller:
  installPlugins:
    - kubernetes:1.31.3
    - workflow-aggregator:2.6
    - git:4.10.2
    - configuration-as-code:1414.v878271fc496f
    
  adminUser: "admin"
  adminPassword: "admin"  
  
  nodePort: 32100      
  serviceType: NodePort   
  # jenkinsUrl: "http://jenkins:8080" 
  
agent:
  jenkinsTunnel: "jenkins-agent:50000"   

persistence:
  enabled: false
